#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

declare \
    real_home_dir

real_home_dir="$(
    getent \
        passwd \
        "${USER}" \
    | cut \
        --delimiter=: \
        --fields=6
)"

zenity \
        --warning \
        --title='Oh Snap! The QXmlEdit snap is no longer supported as of 16 April 2021' \
        --text='<b>WARNING:</b> \\n \\n <b>The QXmlEdit snap is no longer supported as of 16 April 2021</b> \\n \\n Please uninstall the QXmlEdit snap and install from one of the supported sources at <a href="https://qxmledit.org/info.html"> QXmlEdit Info and Downloads page</a>. It will not receive any more security or normal updates.' \
        --width=600 \
        --icon-name=dialog-warning

# Finally run the next part of the command chain
exec "${@}"