name: qxmledit # you probably want to 'snapcraft register <name>'
version: latest # just for humans, typically '1.2+git' or '1.3.2'
version-script: git -C parts/qxmledit/src describe --always --dirty --tags
summary: QXmlEdit is a simple XML editor based on Qt libraries. # 79 char long summary
description: |
  QXmlEdit is a simple XML editor based on Qt libraries. Its main features are unusual data visualization modes, nice XML manipulation and presentation and it is multi platform. It can split very big XML files into fragments, and compare XML and XSD files. It was born on Google code (https://code.google.com/p/qxmledit).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

icon: images/qxmledit.svg
architectures:
  - build-on: amd64
  - build-on: i386
  - build-on: arm64
apps:
  qxmledit:
    command: desktop-launch $SNAP/bin/qxmledit
    desktop: share/${SNAPCRAFT_PROJECT_NAME}/QXmlEdit.desktop
    plugs:
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - opengl
      - home
      - removable-media

parts:
  qxmledit:
    plugin: qmake
    qt-version: qt5
    options:
      - CONFIG+=release
      - QXMLEDIT_INST_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/bin
      - QXMLEDIT_INST_DATA_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME
      - QXMLEDIT_INST_DOC_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME/doc
      - QXMLEDIT_INST_LIB_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/lib
      - QXMLEDIT_INST_INCLUDE_DIR=/snap/$SNAPCRAFT_PROJECT_NAME/current/share/$SNAPCRAFT_PROJECT_NAME/include
    source: https://github.com/lbellonda/qxmledit.git
    source-depth: 50
    build-packages:
      - build-essential
      - libgl1-mesa-dev
      - mesa-common-dev
      - qttools5-dev-tools
      - qtdeclarative5-dev
      - libqt5svg5-dev
      - libqt5xmlpatterns5-dev
      - libqwtplot3d-qt5-dev
      - libqt5opengl5-dev
    override-build: |
      snapcraftctl build
      sed -i 's|Icon=qxmledit|Icon=\${SNAP}/meta/gui/icon.svg|' "${SNAPCRAFT_PART_INSTALL}"/snap/"${SNAPCRAFT_PROJECT_NAME}"/current/share/"${SNAPCRAFT_PROJECT_NAME}"/QXmlEdit.desktop
    stage-packages:
      - libqt5svg5
      - libqt5xmlpatterns5
      - libqt5sql5-sqlite
      - libqt5sql5-mysql
      - libglu1-mesa
      - libqt5opengl5
      - libqt5printsupport5
      - libqt5xml5
      - libqwtplot3d-qt5-0
      - libgcc1
      - libqt5core5a
      - libqt5gui5
      - libqt5widgets5
      - libstdc++6
      - zlib1g
    stage:
      - -lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
      - -lib/x86_64-linux-gnu/libpng12.so.0.54.0
      - -usr/lib/x86_64-linux-gnu/glib-2.0/gio-querymodules
      - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-resources
      - -usr/lib/x86_64-linux-gnu/glib-2.0/glib-compile-schemas
      - -usr/lib/x86_64-linux-gnu/libLLVM-6.0.so.1
      - -usr/lib/x86_64-linux-gnu/libcups.so.2
      - -usr/lib/x86_64-linux-gnu/libdrm.so.2.4.0
      - -usr/lib/x86_64-linux-gnu/libdrm_amdgpu.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libdrm_intel.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libdrm_nouveau.so.2.0.0
      - -usr/lib/x86_64-linux-gnu/libdrm_radeon.so.1.0.1
      - -usr/lib/x86_64-linux-gnu/libelf-0.165.so
      - -usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
      - -usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
      - -usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
      - -usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.2
      - -usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
      - -usr/share/doc/libcups2/changelog.Debian.gz
      - -usr/share/doc/libdrm-common/changelog.Debian.gz
      - -usr/share/doc/libelf1/changelog.Debian.gz
      - -usr/share/doc/libglib2.0-0/changelog.Debian.gz
      - -usr/share/doc/libjpeg-turbo8/changelog.Debian.gz
      - -usr/share/doc/libllvm6.0/changelog.Debian.gz
      - -usr/share/doc/libpng12-0/changelog.Debian.gz
      - -usr/share/doc/x11-common/changelog.gz
      - -usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
      - -usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
      - -usr/share/X11/locale/C/Compose
      - -usr/share/X11/locale/C/XLC_LOCALE
      - -usr/share/X11/locale/am_ET.UTF-8/Compose
      - -usr/share/X11/locale/am_ET.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/armscii-8/Compose
      - -usr/share/X11/locale/armscii-8/XLC_LOCALE
      - -usr/share/X11/locale/compose.dir
      - -usr/share/X11/locale/cs_CZ.UTF-8/Compose
      - -usr/share/X11/locale/cs_CZ.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/el_GR.UTF-8/Compose
      - -usr/share/X11/locale/el_GR.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/en_US.UTF-8/Compose
      - -usr/share/X11/locale/en_US.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/fi_FI.UTF-8/Compose
      - -usr/share/X11/locale/fi_FI.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/georgian-academy/Compose
      - -usr/share/X11/locale/georgian-academy/XLC_LOCALE
      - -usr/share/X11/locale/georgian-ps/Compose
      - -usr/share/X11/locale/georgian-ps/XLC_LOCALE
      - -usr/share/X11/locale/ibm-cp1133/Compose
      - -usr/share/X11/locale/ibm-cp1133/XLC_LOCALE
      - -usr/share/X11/locale/iscii-dev/Compose
      - -usr/share/X11/locale/iscii-dev/XLC_LOCALE
      - -usr/share/X11/locale/isiri-3342/Compose
      - -usr/share/X11/locale/isiri-3342/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-1/Compose
      - -usr/share/X11/locale/iso8859-1/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-10/Compose
      - -usr/share/X11/locale/iso8859-10/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-11/Compose
      - -usr/share/X11/locale/iso8859-11/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-13/Compose
      - -usr/share/X11/locale/iso8859-13/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-14/Compose
      - -usr/share/X11/locale/iso8859-14/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-15/Compose
      - -usr/share/X11/locale/iso8859-15/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-2/Compose
      - -usr/share/X11/locale/iso8859-2/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-3/Compose
      - -usr/share/X11/locale/iso8859-3/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-4/Compose
      - -usr/share/X11/locale/iso8859-4/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-5/Compose
      - -usr/share/X11/locale/iso8859-5/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-6/Compose
      - -usr/share/X11/locale/iso8859-6/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-7/Compose
      - -usr/share/X11/locale/iso8859-7/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-8/Compose
      - -usr/share/X11/locale/iso8859-8/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-9/Compose
      - -usr/share/X11/locale/iso8859-9/XLC_LOCALE
      - -usr/share/X11/locale/iso8859-9e/Compose
      - -usr/share/X11/locale/iso8859-9e/XLC_LOCALE
      - -usr/share/X11/locale/ja.JIS/Compose
      - -usr/share/X11/locale/ja.JIS/XLC_LOCALE
      - -usr/share/X11/locale/ja.SJIS/Compose
      - -usr/share/X11/locale/ja.SJIS/XLC_LOCALE
      - -usr/share/X11/locale/ja/Compose
      - -usr/share/X11/locale/ja/XLC_LOCALE
      - -usr/share/X11/locale/ja_JP.UTF-8/Compose
      - -usr/share/X11/locale/ja_JP.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/km_KH.UTF-8/Compose
      - -usr/share/X11/locale/km_KH.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/ko/Compose
      - -usr/share/X11/locale/ko/XLC_LOCALE
      - -usr/share/X11/locale/ko_KR.UTF-8/Compose
      - -usr/share/X11/locale/ko_KR.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/koi8-c/Compose
      - -usr/share/X11/locale/koi8-c/XLC_LOCALE
      - -usr/share/X11/locale/koi8-r/Compose
      - -usr/share/X11/locale/koi8-r/XLC_LOCALE
      - -usr/share/X11/locale/koi8-u/Compose
      - -usr/share/X11/locale/koi8-u/XLC_LOCALE
      - -usr/share/X11/locale/locale.alias
      - -usr/share/X11/locale/locale.dir
      - -usr/share/X11/locale/microsoft-cp1251/Compose
      - -usr/share/X11/locale/microsoft-cp1251/XLC_LOCALE
      - -usr/share/X11/locale/microsoft-cp1255/Compose
      - -usr/share/X11/locale/microsoft-cp1255/XLC_LOCALE
      - -usr/share/X11/locale/microsoft-cp1256/Compose
      - -usr/share/X11/locale/microsoft-cp1256/XLC_LOCALE
      - -usr/share/X11/locale/mulelao-1/Compose
      - -usr/share/X11/locale/mulelao-1/XLC_LOCALE
      - -usr/share/X11/locale/nokhchi-1/Compose
      - -usr/share/X11/locale/nokhchi-1/XLC_LOCALE
      - -usr/share/X11/locale/pt_BR.UTF-8/Compose
      - -usr/share/X11/locale/pt_BR.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/pt_PT.UTF-8/Compose
      - -usr/share/X11/locale/pt_PT.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/ru_RU.UTF-8/Compose
      - -usr/share/X11/locale/ru_RU.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/sr_CS.UTF-8/Compose
      - -usr/share/X11/locale/sr_CS.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/tatar-cyr/Compose
      - -usr/share/X11/locale/tatar-cyr/XLC_LOCALE
      - -usr/share/X11/locale/th_TH.UTF-8/Compose
      - -usr/share/X11/locale/th_TH.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/th_TH/Compose
      - -usr/share/X11/locale/th_TH/XLC_LOCALE
      - -usr/share/X11/locale/tscii-0/Compose
      - -usr/share/X11/locale/tscii-0/XLC_LOCALE
      - -usr/share/X11/locale/vi_VN.tcvn/Compose
      - -usr/share/X11/locale/vi_VN.tcvn/XLC_LOCALE
      - -usr/share/X11/locale/vi_VN.viscii/Compose
      - -usr/share/X11/locale/vi_VN.viscii/XLC_LOCALE
      - -usr/share/X11/locale/zh_CN.UTF-8/Compose
      - -usr/share/X11/locale/zh_CN.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/zh_CN.gb18030/Compose
      - -usr/share/X11/locale/zh_CN.gb18030/XLC_LOCALE
      - -usr/share/X11/locale/zh_CN.gbk/Compose
      - -usr/share/X11/locale/zh_CN.gbk/XLC_LOCALE
      - -usr/share/X11/locale/zh_CN/Compose
      - -usr/share/X11/locale/zh_CN/XLC_LOCALE
      - -usr/share/X11/locale/zh_HK.UTF-8/Compose
      - -usr/share/X11/locale/zh_HK.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/zh_HK.big5/Compose
      - -usr/share/X11/locale/zh_HK.big5/XLC_LOCALE
      - -usr/share/X11/locale/zh_HK.big5hkscs/Compose
      - -usr/share/X11/locale/zh_HK.big5hkscs/XLC_LOCALE
      - -usr/share/X11/locale/zh_TW.UTF-8/Compose
      - -usr/share/X11/locale/zh_TW.UTF-8/XLC_LOCALE
      - -usr/share/X11/locale/zh_TW.big5/Compose
      - -usr/share/X11/locale/zh_TW.big5/XLC_LOCALE
      - -usr/share/X11/locale/zh_TW/Compose
      - -usr/share/X11/locale/zh_TW/XLC_LOCALE
      - -usr/share/doc/libx11-6/changelog.Debian.gz
      - -usr/share/doc/libx11-data/changelog.Debian.gz
      - -usr/share/doc/libx11-xcb1/changelog.Debian.gz
      - -usr/share/doc/libxkbcommon0/changelog.Debian.gz
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current: /
  desktop-qt5:
